import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecNormalize, DummyVecEnv
import time

# --- Constants ---
# Use the same Environment ID
ENV_ID = "Walker2d-v4"
# Path to the saved model and stats.
# !!! IMPORTANT: Replace with the actual filenames generated by the training script !!!
MODEL_PATH = "../../logs_and_models/models/ppo_Walker2d-v4_2000000_1763296143.zip"
STATS_PATH = "../../logs_and_models/models/ppo_Walker2d-v4_2000000_1763296143_vecnormalize.pkl"

# --- Load the saved model and environment stats ---
print("Loading model and environment stats...")
# First, load the saved statistics
eval_env = VecNormalize.load(STATS_PATH, DummyVecEnv([lambda: gym.make(ENV_ID, render_mode="human")]))

# Set the environment to evaluation mode (don't update stats)
eval_env.training = False
# Don't normalize rewards during evaluation
eval_env.norm_reward = False

# Load the PPO agent
model = PPO.load(MODEL_PATH, env=eval_env)
print("Model loaded successfully.")

# --- Run the evaluation loop ---
obs = eval_env.reset()
episodes = 5
print(f"Running {episodes} evaluation episodes...")

for _ in range(episodes):
    terminated = False
    truncated = False
    average_speed = 0
    while not terminated and not truncated:
        # Get the action from the model (deterministic=True for consistent behavior)
        action, _states = model.predict(obs, deterministic=True)

        # Take the action in the environment
        obs, reward, terminated, info = eval_env.step(action)
        average_speed += info[0].get('x_velocity', 0.0)
    average_speed /= 1000.0
    print(average_speed)


print("Evaluation finished.")
eval_env.close()
